/* tslint:disable */
/* eslint-disable */
/**
 * Coska Chat API
 * This API exposes endpoints to manage Coska Chat.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: admin@coska.chat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MessageDto
 */
export interface MessageDto {
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    'roomId'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    'senderId'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    'payload'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    'timestamp'?: string;
}

