/* tslint:disable */
/* eslint-disable */
/**
 * Coska Chat API
 * This API exposes endpoints to manage Coska Chat.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: admin@coska.chat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoomDto
 */
export interface RoomDto {
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    'lastMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    'lastSentUserId'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RoomDto
     */
    'participants'?: Array<string>;
}

