/* tslint:disable */
/* eslint-disable */
/**
 * Coska Chat API
 * This API exposes endpoints to manage Coska Chat.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: admin@coska.chat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'gptKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'type'?: string;
}

