# Name of workflow as seen in Github actions tab
name: dev-build
# Run workflow only on push to dev branch
on:
  push:
    branches:
      - develop

env:
  REACTCONFIG: {"SourceDir":"src\","DistributionDir":"build","BuildCommand":"npm run-script build","StartCommand":"npm run-script start"}
  AWSCLOUDFORMATIONCONFIG: {"configLevel":"project","useProfile":false,"profileName":"default","accessKeyId":"${{ secrets.AWS_ACCESS_KEY_ID }}","secretAccessKey":"${{ secrets.AWS_SECRET_ACCESS_KEY }}","region":"${{ secrets.AWS_REGION }}"}
  AMPLIFY: {"projectName":"headlessProjectName","appId":"amplifyServiceProjectAppId","envName":"myenvname","defaultEditor":"code"}
  FRONTEND: {"frontend":"javascript","framework":"react","config":$REACTCONFIG}
  PROVIDERS: {"awscloudformation":$AWSCLOUDFORMATIONCONFIG}

jobs:
  # To build the project
  build-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        run: npm install
      - name: Installing amplify
        run: npm install aws-amplify
      - name: Pull amplify environment
        run: amplify pull --amplify $AMPLIFY --frontend $FRONTEND --providers $PROVIDERS --yes
      - name: Building project
        run: npm run build
